### ISSUE TITLE
2016-9-3沽源坝上草原活动

### ISSUE THREAD

**Issue by congcong666** [congcong666/outdoor#1]
地点：河北省张家口市沽源县坝上草原
时间：2016-9-3至2016-9-4
成员：雷明 阿来 高崇 慧慧 国宾

景点介绍：
沽源草原北接内蒙古草原，与丰宁坝上和围场张北坝上形成三足鼎立之势。

主要景点金莲山庄：距沽源泉县城50公里，距张家口230公里，距离北京340公里。
海拔1800米，山庄总面积6万亩，是塞外天然野生植物园。夏季的金莲山庄蜂飞蝶舞，泉水奔涌，云蒸雾露，风光无限。

沽源的坝上草原不同于丰宁坝上草原，丰宁草原因知名度较高，开发过度，植被已经稀疏。
而沽源坝上草原则是天然原生态草原，著名的闪电源就是在沽源县境内。

从张家口往北去往沽源县的路上，会经过著名的“草原天路”——中国66号公路。
据说美到灼伤眼睛。
![image](https://cloud.githubusercontent.com/assets/5513222/18193015/1f57b122-710c-11e6-8237-26ec25b26f18.png)

![image](https://cloud.githubusercontent.com/assets/5513222/18193133/1f555016-710d-11e6-9a8a-798e703b68f8.png)

**行程安排**
9月3日行程安排
5:30 回龙观
6:30 通州果园
7:00-10:00 京藏高速北京-张家口段、张承高速(到达张家口)
10:00-12:00 草原天路(到达沽源县)
12:00-13:00 安排住宿以及午餐
13:00-24:00 玩

9月4日行程安排
// todo...

**Comment by congcong666** [comment]
天气情况
9-3 张家口沽源县  多云转阴 11-23度
9-4 张家口沽源县  阵雨 14-25度

**Comment by congcong666** [comment]
着装建议
据说天气会比较冷，温度推测在20摄氏度左右，建议下衣长裤，上衣长袖或短袖均可。
另外建议带一件长袖外衣。

**Comment by congcong666** [comment]
装备携带
由于这次准备不是很充分，再加上天气不太好可能会下雨，就不露营了。大家住农家院就行。
有我和阿来的2个帐篷休憩足够用了。
请检查以下必备物品是否带齐：
1.身份证(可能会遇到怪警察叔叔)
2.少量现金
3.移动电源
4.数据线
5.相机
6.消毒药(我带了)
其他看自己需要自行携带

**Comment by lanleiming** [comment]
防蚊的（我带）
扑克（我带）
水
墨镜
创可贴
